# Generated by Django 4.1.3 on 2022-12-01 03:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchallenge',
            unique_together={('challenge', 'participant')},
        ),
    ]
